default_platform(:mac)

platform :mac do
  desc "release to app store"
  lane :release_workbench do
      api_key = app_store_connect_api_key(
          key_id: ENV["KEY_ID"],
          issuer_id: ENV["ISSUER_ID"],
          key_filepath: ENV["PRIVATE_KEY_PATH"]
      )

      upload_to_testflight(
        api_key: api_key,
        pkg: ENV["PKG_PATH"]
      )

      deliver(
        api_key: api_key,
        skip_binary_upload: true,
        skip_metadata: false,
        skip_screenshots: true,
        release_notes: { "en-US" => ENV["RELEASE_NOTES"] },
        submit_for_review: false,
        automatic_release: false
      )
  end
end
