name: Build dolt-workbench for platform and upload to release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: GitHub Release Version Number
        required: true
        type: string
      platform:
        description: Platform to target
        required: true
        options:
          - windows
          - linux
          - mas
          - dmg

  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  set-variables:
    runs-on: ubuntu-22.04
    steps:
      - name: Set variables for workflow run
        run: |
          case ${{ inputs.platform }} in    
            windows)
              echo "build_config_file=web/build/builder-win-config.yaml" >> $GITHUB_OUTPUT
              echo "runner=windows-2022" >> $GITHUB_OUTPUT
              echo "
              ;;
            linux)
              echo "build_config_file=web/build/builder-linux-config.yaml" >> $GITHUB_OUTPUT
              echo "runner=ubuntu-22.04" >> $GITHUB_OUTPUT
              
              ;;
            mas)
              echo "build_config_file=web/build/builder-mas-config" >> $GITHUB_OUTPUT
              echo "runner=macos-14" >> $GITHUB_OUTPUT
              
              ;;
            dmg)
              echo "build_config_file=web/build/builder-dmg-config" >> $GITHUB_OUTPUT
              echo "runner=macos-14" >> $GITHUB_OUTPUT
              
              ;;
              
          
          if [ ${{ inputs.platform }} == "windows" ]
          then
            echo "build_config_file=web/build/builder-win-config.yaml" >> $GITHUB_OUTPUT
          elif [ ${{ inputs.
            
  
    
    
