name: Create Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: GitHub release version
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        description: GitHub release version
        required: true
        type: string

jobs:
  create-release-notes:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Release Notes Generator
        uses: actions/checkout@v3
        with:
          repository: dolthub/release-notes-generator

      - name: Install Dependencies
        run: sudo ./install-deps.sh
        env:
          PERL_MM_USE_DEFAULT: 1

      - name: Create Notes
        id: create-notes
        run: |
          echo "notes=$(./gen_release_notes.pl dolthub/dolt-workbench v${{ inputs.version }})" >> $GITHUB_OUTPUT
      - name: Post Changelog to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          body: ${{ steps.create-notes.outputs.notes }}
