name: Publish to Windows App Store
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        required: true
        type: string
      workflow-run-id:
        description: Workflow Run ID
        required: true
        type: string
  workflow_call:
    inputs:
      release-version:
        description: Release version
        required: true
        type: string
      workflow-run-id:
        description: Workflow Run ID
        required: false
        default: ${{ github.run_id }}
        type: string

jobs:
  publish-windows-store:
    name: Publish to Windows app store
    runs-on: windows-2022
    steps:
      - name: Download .appx artifact
        id: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: windows-${{ inputs.release-version }}
          path: dist
          github-token: ${{ github.token }}
          run-id: ${{ inputs.workflow-run-id }}

      - name: debug
        run: |
          mv ${{ steps.download-artifact.outputs.download-path }}/Dolt-Workbench-win-x64.appx ${{ steps.download-artifact.outputs.download-path }}/Dolt-Workbench-win-x64-draft.appx

      - name: Publish to Microsoft Store
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          APP_ID: ${{ secrets.STORE_APP_ID }}
          APPX_PATH: ${{ steps.download-artifact.outputs.download-path }}
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted

          Install-Module -Name StoreBroker

          $clientSecret = ConvertTo-SecureString $env:CLIENT_SECRET -AsPlainText -Force

          $cred = New-Object System.Management.Automation.PSCredential $env:CLIENT_ID, $clientSecret

          Set-StoreBrokerAuthentication -TenantId $env:TENANT_ID -Credential $cred -Verbose

          $submission = New-ApplicationSubmission -AppId $env:APP_ID -Force
          
          $submission.listings."en-us".baseListing.releaseNotes = "this is a test submission"
          
          Write-Host "Modified release notes: $($submission.listings.'en-us'.baseListing.releaseNotes)"
          
          ls $env:APPX_PATH
          
          $updatedSubmission = Set-ApplicationSubmission -AppId $env:APP_ID -UpdatedSubmission $submission
          
#          Set-SubmissionPackage -PackagePath $env:APPX_PATH/Dolt-Workbench-win-x64-draft.appx -UploadUrl ($updatedSubmission.fileUploadUrl)
          



#          $submission = Add-ApplicationPackage -AppId $env:APP_ID -Submission $submission -FilePath $env:APPX_PATH
#
#          $submission = Update-ApplicationSubmission -AppId $env:APP_ID -Submission $submission
