name: Publish to App Store
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        required: true
        type: string
      workflow-run-id:
        description: Workflow Run ID
        required: true
        type: string
      platform:
        description: mac or windows
        required: true
        type: choice
        options:
          - mac
          - windows

  workflow_call:
    inputs:
      release-version:
        description: Release version
        required: true
        type: string
      workflow-run-id:
        description: Workflow Run ID
        required: false
        default: ${{ github.run_id }}
        type: string
      platform:
        description: mac or windows
        required: true
        type: string

jobs:
  publish-mac-store:
    if: ${{ inputs.platform == 'mac' }}
    name: Publish to Mac app store
    runs-on: macos-14
    steps:
      - name: Download .pkg artifact
        id: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: mac-${{ inputs.release-version }}
          path: dist
          github-token: ${{ github.token }}
          run-id: ${{ inputs.workflow-run-id }}

      - name: Get PKG path
        id: get-pkg-path
        run: |
          PKG=$(ls dist | head -n1)
          echo "pkg_path=${{ steps.download-artifact.outputs.download-path }}/$PKG" >> $GITHUB_OUTPUT

      - name: Make private key file
        id: make-key-file
        run: |
          echo ${{ secrets.APPSTORE_API_PRIVATE_KEY }} > AuthKey_${{ vars.APPSTORE_API_KEY_ID }}.p8
          echo "key_path=$(pwd)/AuthKey_${{ vars.APPSTORE_API_KEY_ID }}.p8" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Install fastlane
        run: gem install fastlane

      - name: Publish to Mac store
        env:
          KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
          ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
          PRIVATE_KEY_PATH: ${{ steps.make-key-file.outputs.key_path }}
          PKG_PATH: ${{ steps.get-pkg-path.outputs.pkg_path }}
          RELEASE_NOTES: "Bug fixes and improvements"
        run: bundle exec fastlane release_workbench

  publish-windows-store:
    if: ${{ inputs.platform == 'windows' }}
    name: Publish to Windows app store
    runs-on: windows-2022
    steps:
      - name: Download .appx artifact
        id: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: windows-${{ inputs.release-version }}
          path: dist
          github-token: ${{ github.token }}
          run-id: ${{ inputs.workflow-run-id }}

      - name: Publish to Microsoft Store
        shell: pwsh
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          APP_ID: ${{ secrets.STORE_APP_ID }}
          APPX_PATH: ${{ steps.download-artifact.outputs.download-path }}
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted

          Install-Module -Name StoreBroker

          $clientSecret = ConvertTo-SecureString $env:CLIENT_SECRET -AsPlainText -Force

          $cred = New-Object System.Management.Automation.PSCredential $env:CLIENT_ID, $clientSecret

          Set-StoreBrokerAuthentication -TenantId $env:TENANT_ID -Credential $cred

          $submission = New-ApplicationSubmission -AppId $env:APP_ID -Force
          
          $submission.listings."en-us".baseListing.releaseNotes = "this is a test submission"
          
          Write-Host "Modified release notes: $($submission.listings.'en-us'.baseListing.releaseNotes)"
          
          ls $env:APPX_PATH
          
          $updatedSubmission = Set-ApplicationSubmission -AppId $env:APP_ID -UpdatedSubmission $submission
          
#          Set-SubmissionPackage -PackagePath $env:APPX_PATH/Dolt-Workbench-win-x64-draft.appx -UploadUrl ($updatedSubmission.fileUploadUrl)
          



#          $submission = Add-ApplicationPackage -AppId $env:APP_ID -Submission $submission -FilePath $env:APPX_PATH
#
#          $submission = Update-ApplicationSubmission -AppId $env:APP_ID -Submission $submission
