name: Release dolt-workbench for Windows
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: GitHub Release Version Number
        required: true
        type: string

jobs:
  update-windows-version:
    uses: ./.github/workflows/bump-build-version.yaml
    with:
      build-config-file: web/build/builder-win-config.yaml

  build-windows:
    needs: update-windows-version
    name: Build Windows release version
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Next build
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install graphql-server dependencies
        working-directory: graphql-server
        run: |
          yarn 
          yarn build

      - name: Install web dependencies
        working-directory: web
        run: |
          yarn
          yarn download:dolt

      - name: Build Windows package
        working-directory: web
        run: |
          yarn build:win
          ls dist

      - name: Upload package to Release ${{ inputs.release-version }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.release-version }}
          files: /web/dist/Dolt-Workbench-win-x64.exe




