name: Release dolt-workbench for Windows
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: GitHub Release Version Number
        required: true
        type: string

jobs:
  update-windows-version:
    uses: ./.github/workflows/bump-build-version.yaml
    with:
      build-config-file: web/build/builder-win-config.yaml

  build-windows:
    needs: update-windows-version
    name: Build Windows release version
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: 'yarn'
          cache-dependency-path: |
            graphql-server/yarn.lock
            web/yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn global cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/berry/cache
            .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            web/renderer/.next/cache
            web/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('web/renderer/next.config.js', 'web/package.json', 'web/yarn.lock') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Install graphql-server dependencies
        working-directory: graphql-server
        run: |
          yarn 
          yarn build

      - name: Install web dependencies
        working-directory: web
        run: |
          yarn
          yarn download:dolt

      - name: Build Windows package
        working-directory: web
        run: |
          yarn build:win
          ls dist

      - name: Upload package to Release ${{ inputs.release-version }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.release-version }}
          files: ${{ github.workspace }}/web/dist/Dolt-Workbench-win-x64.exe

