name: Build dolt-workbench for Mac App Store
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: GitHub Release Version Number
        required: true
        type: string

  workflow_call:
    inputs:
      release-version:
        description: Github Release Version Number
        required: true
        type: string

jobs:
  update-mas-version:
    uses: ./.github/workflows/bump-build-version.yaml
    with:
      build-config-file: web/build/builder-mas-config.yaml

  build-mas:
    needs: update-mas-version
    name: Build Mac App Store release version
    runs-on: macos-14
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Download provisioning profiles
        id: download-provisioning-profiles
        uses: apple-actions/download-provisioning-profiles@v4
        with:
          bundle-id: com.dolthub.dolt-workbench
          profile-type: MAC_APP_STORE
          issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ vars.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Move provision profile to build directory
        run: |
          JSON='${{ steps.download-provisioning-profiles.outputs.profiles }}'
          UDID=$(echo $JSON | jq -r '.[0].udid')
          mv "$HOME/Library/MobileDevice/Provisioning Profiles/$UDID.provisionprofile" "${{ github.workspace }}/web/build/mac/MacAppStore.provisionprofile"

      - name: Import codesign certificates
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            web/renderer/.next/cache
            web/.next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('web/renderer/next.config.js', 'web/package.json', 'web/yarn.lock') }}
          restore-keys: |
            nextjs-${{ runner.os }}-

      - name: Install graphql-server dependencies
        working-directory: graphql-server
        run: |
          yarn 
          yarn build

      - name: Install web dependencies
        working-directory: web
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          yarn
          yarn download:dolt

      - name: Build MAS package
        working-directory: web
        run: |
          yarn build:mas
          echo "DIST:"
          ls dist
          echo "inside mas-universal"
          ls dist/mas-universal

#      - name: Upload package to Release ${{ inputs.release-version }}
#        uses: softprops/action-gh-release@v2
#        with:
#          tag_name: v${{ inputs.release-version }}
#          files: ${{ github.workspace }}/web/dist/Dolt-Workbench-win-x64.exe
#
